### PR TITLE
#149 changes oasp templates Long to IdReference<entity>

### LINKED ISSUE #149: Change OASP templates to use IdReference<Entity> as Eto to Eto references
Currently, we are using Long to express references between Eto's.
The latest version of the OASP introduced a new type called `IdReference<Entity>` to express references between Eto's, which are more readable. 
This has to be adapted in the templates.

### PR DESCRIPTION
**Pull request by sanjaykumarcg**
Fixes #149.

I have done the changes in OaspUtil.java and functions.ftl file and replace Long with IdRef<Entity type>

@devonfw/cobigen

### CODE REVIEW

**Comment by jdiazgon** [comment]
I tried with the newest templates and I was getting some compilation errors. Maybe you could check with the new 3.0.0 templates after PR #770 gets merged.

**Comment by maybeec** [comment]
what is the status here? Does it work? If not, what is the remaining work to be done?

**Comment by jdiazgon** [comment]
It needs some more work as I have just seen there are multiple references to `Long` on the templates.

**Comment by jdiazgon** [comment]
I'm closing this PR as it got on hold too much time and a lot of work is still pending.

**Pull request closed without merging**
