### PR TITLE
Added merging annotations to javamerge functionality

### LINKED ISSUE #430: Javamerge does not merge annotations
Currently, the java merger does not merge annotations.
So far there are two restriction after implementation of this ticket:
1. Annotations are not merged recursively as it's not easy to identify "matching" annotations within an array
2. [Repeating annotations](https://docs.oracle.com/javase/tutorial/java/annotations/repeating.html) defined next to each other could not be identified / differentiated for a proper merge, therefore, we need to overwrite / ignore all annotations of a given scope as a block

*Acceptance Criteria*
* [x] Annotations, which are not yet there should be added
* [x] All annotations should be replaced or not replaced
* [x] Annotations should be merged the same for fields, methods, classes

### PR DESCRIPTION
**Pull request by MikeSchumacherCapgemini**
Adresses #430.

Implements

* Test case for annotation merging
* Additional method for merging annotations
* updated/deleted old comments/javadoc

### CODE REVIEW

**Comment by maybeec** [comment]
Please also come up with a test of more complex annotations like described in #290.
What is the actual behavior there?

**Comment by jdiazgon** [comment]
From my point of view, seems fine.

**Comment by MikeSchumacherCapgemini** [comment]
Complex annotation test is a bit awkward but qdox does not support a way to get further data about anything within an AnnotationValue after getProperty() so checking the string value was the only way i found how this can be tested.

**Comment by maybeec** [comment]
Two things here:

1. Annotations, should be left as is, when it comes to type declarations. In your test, the annotations are after generation printed with full qualified names, while beforehand they had just been printed with simple types. Try to keep the original declaration. I think Qdox also has an interface for this. There are multiple getters for types.
2. Annotations here are just overwritten entirely or not at all. What about recursively merging arrays of 
annotations?
3. Be careful, in Java8 annotations can be repeated: https://docs.oracle.com/javase/tutorial/java/annotations/repeating.html So just comparing as of type of the annotation, you cannot start merging. You have to check whether the annotation is repeatable.

All this issues need to define heuristics how to compare annotations. The easiest way would be to compare the "value", but most often if there is a annotation array, the annotations come with clearly distinguishable values. We can for example introduce something like "if an annotation has 'name' or 'key' as an attribute, the values of such attributes are used as identifier (fallback 'value' value)". What do you think? This is up to discussion.

**Comment by maybeec** [comment]
closed in favor of  #1053

**Pull request closed without merging**
